config/routes.rb
Rails.application.routes.draw do
  
  root to: 'welcome#index'
  resources :sales
  resources :inventories
  resources :products
  resources :reports
  resources :partners do
   end
  

end

app/models/partner.rb
class Partner < ActiveRecord::Base
	has_many :products
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_action :set_partner, only: [:show, :edit, :update, :destroy]

  # GET /partners
  # GET /partners.json
  def index
    @partners = Partner.all
  end

  # GET /partners/1
  # GET /partners/1.json
  def show
  end

  # GET /partners/new
  def new
    @partner = Partner.new
  end

  # GET /partners/1/edit
  def edit
  end

  # POST /partners
  # POST /partners.json
  def create
    @partner = Partner.new(partner_params)

    respond_to do |format|
      if @partner.save
        format.html { redirect_to @partner, notice: 'Partner was successfully created.' }
        format.json { render :show, status: :created, location: @partner }
      else
        format.html { render :new }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partners/1
  # PATCH/PUT /partners/1.json
  def update
    respond_to do |format|
      if @partner.update(partner_params)
        format.html { redirect_to @partner, notice: 'Partner was successfully updated.' }
        format.json { render :show, status: :ok, location: @partner }
      else
        format.html { render :edit }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partners/1
  # DELETE /partners/1.json
  def destroy
    @partner.destroy
    respond_to do |format|
      format.html { redirect_to partners_url, notice: 'Partner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partner
      @partner = Partner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def partner_params
      params.require(:partner).permit(:name, :telephone, :email, :business, :rent)
    end
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/views/partners/_form.html.erb
<%= form_for(@partner) do |f| %>
  <% if @partner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@partner.errors.count, "error") %> prohibited this partner from being saved:</h2>

      <ul>
      <% @partner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br>
    <%= f.text_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :business %><br>
    <%= f.text_field :business %>
  </div>
  <div class="field">
    <%= f.label :rent %><br>
    <%= f.number_field :rent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/partners/edit.html.erb
<h1>Editing Partner</h1>

<%= render 'form' %>

<%= link_to 'Show', @partner %> |
<%= link_to 'Back', partners_path %>

app/views/partners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Partners</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Telephone</th>
      <th>Email</th>
      <th>Business</th>
      <th>Rent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @partners.each do |partner| %>
      <tr>
        <td><%= partner.name %></td>
        <td><%= partner.telephone %></td>
        <td><%= partner.email %></td>
        <td><%= partner.business %></td>
        <td><%= partner.rent %></td>
        <td><%= link_to 'Show', partner %></td>
        <td><%= link_to 'Edit', edit_partner_path(partner) %></td>
        <td><%= link_to 'Destroy', partner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Partner', new_partner_path %>

app/views/partners/new.html.erb
<h1>New Partner</h1>

<%= render 'form' %>

<%= link_to 'Back', partners_path %>

app/views/partners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @partner.name %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @partner.telephone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @partner.email %>
</p>

<p>
  <strong>Business:</strong>
  <%= @partner.business %>
</p>

<p>
  <strong>Rent:</strong>
  <%= @partner.rent %>
</p>

<%= link_to 'Edit', edit_partner_path(@partner) %> |
<%= link_to 'Back', partners_path %>